### ISSUE TITLE
make mobile responsive

### ISSUE THREAD

**Issue by shyamtawli** [shyamtawli/recipes#2]
Make the website mobile friendly, don't change any styling.

**Comment by evirusky** [comment]
you can use bootstrap to make the website responsive. You can get more information  https://react-bootstrap.github.io/getting-started/introduction .

**Comment by Akashzxr** [comment]
@shyamtawli do you have any design for mobile.

**Comment by shyamtawli** [comment]
@Akashzxr No but if you have any there share it.
